spring:
  jpa.hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/usuario?createDatabaseIfNotExist=true
    username: root
    password: toor
  hikari:
    connection_timeout: 60000
    maximum-pool-size: 5
server:
  port: 8081