spring:
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_example?createDatabaseIfNotExist=true
    username: root
    password: toor
server:
  port: 8085